on:
  schedule:
    # Schedule to run on the first Sunday of every month at 00:00 UTC
    - cron: '0 0 * * 0#1'
  workflow_call:
    inputs:
      PROJECT_NAME:
        type: string
        required: true
      ENGAGEMENT:
        type: string
        required: true
    secrets:
      DEFECTDOJO_API_TOKEN:
        required: true

jobs:
  ZapFullScan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: "https://viact.ai" 
          rules_file_name: false  # Skip using a rules file for now
          format: "json"
          artifact_name: "zap_report.json"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.json

      - name: Send ZAP Report to DefectDojo
        run: |
          curl -X POST "https://security-center.viact.net:21443/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
          -F "scan_type=ZAP Scan" \
          -F "engagement=${{ inputs.ENGAGEMENT }}" \
          -F "file=@zap_report.json" \
          -F "active=true" \
          -F "verified=false" \
          -F "close_old_findings=false"
