on:
  schedule:
    # Schedule to run on the first Sunday of every month at 00:00 UTC
    - cron: '0 0 1-7 * 0'

  workflow_dispatch:

jobs:
  ZapFullScan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: 
          - "https://app.viact.ai"
          - "https://api.viact.ai"
          - "https://app.viact.net"
          - "https://api.viact.net"
        engagement:
          - 5  # Engagement ID for app.viact.ai
          - 6  # Engagement ID for api.viact.ai
          - 7  # Engagement ID for app.viact.net
          - 8  # Engagement ID for api.viact.net

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ZAP Full Scan on ${{ matrix.target }}
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: "${{ matrix.target }}"
          rules_file_name: false
          artifact_name: "zap_report_${{ matrix.target }}.json"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3  # Updated to version 3
        with:
          name: zap-report-${{ matrix.target }}
          path: zap_report_${{ matrix.target }}.json

      - name: Send ZAP Report to DefectDojo
        run: |
          curl -X POST "https://security-center.viact.net:21443/api/v2/import-scan/" \
          -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_TOKEN }}" \
          -F "scan_type=ZAP Scan" \
          -F "engagement=${{ matrix.engagement }}" \
          -F "file=@zap_report_${{ matrix.target }}.json" \
          -F "active=true" \
          -F "verified=false" \
          -F "close_old_findings=false"